name: Deploy To Glitch
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Replace Glitch-specific package.json
        run: cp package.json glitch-package.json
      - name: Deploy To Glitch
        uses: kanadgupta/glitch-sync@main
        with:
          project-id: '${{ secrets.PROJECT_ID }}'
          auth-token: '${{ secrets.AUTH_TOKEN }}'
      - name: Delete package.json on Glitch via API
        run: |
          curl -X POST "https://api.glitch.com/projects/${{ secrets.PROJECT_ID }}/remix" \
          -H "Authorization: Bearer ${{ secrets.AUTH_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"mutations":[{"action":"removeFile","path":"package.json"}]}'
